sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stevenchang421/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevenchang421/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Docker-react-env'
  bucket_name: 'elasticbeanstalk-us-east-1-121144070577'
  bucket_path: 'docker-react'
  on:
    branch: main
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
