sudo: required
services:
  - docker

before_install:
  - docker build -t stevenchang421/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stevenchang421/docker-react npm run test
